### ISSUE TITLE
URL query contains semicolon, which is no longer a supported separator; parts of the query may be stripped when parsed; see golang.org/issue/25192

### ISSUE THREAD

**Issue by ketzacoatl** [fabiolb/fabio#955]
I see a bunch of log messages from fabio:

```
invalid log msg: ... http: URL query contains semicolon, which is no longer a supported separator; parts of the query may be stripped when parsed; see golang.org/issue/25192
```

I'm not sure what needs to be done here, or what the originating url query contained, but it reads like an update to the libraries or parsing methods used?

**Comment by ketzacoatl** [comment]
This has probably been fixed in the recent updates to golang and the project dependencies. @tristanmorgan could we do a RC build or similar to test the recent updates?

**Comment by tristanmorgan** [comment]
Sorry for the late reply, I was on vacation. do you have steps to reproduce this error message? doing bit of a search through the code it looks like its from route/table.go addRoute(). What tags for your services are set?

**Comment by tristanmorgan** [comment]
Hi @ketzacoatl, Fabio 1.6.4 is released now. How are you testing this?

**Comment by lcividin** [comment]
Hey just fyi I was seeing this log after upgrading to 1.6.3. I've since updated to 1.6.4 and I no longer see these logs entries. I thought I'd post this as no one else seems to have responded yet. 

I am though still seeing this log still but I doubt that will be worked on anytime soon https://github.com/fabiolb/fabio/issues/407 

Thanks for fixing that one up though
